### ISSUE TITLE
Look for help

### ISSUE THREAD

**Issue by shenshenzhanzhan** [nickmartin1ee7/Maxicode-Decoder#1]
Thanks for  your repo.
Can you give me some advices about decoding Maxicode? I want to know the decoding process of Maxicode.

**Comment by nickmartin1ee7** [comment]
There is documentation about where in a maxicode's string specific information is located.
https://www.neodynamic.com/Products/Help/BarcodeWP1.0/barcodes/MaxiCode.htm
